In [1]:
import numpy as np 

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos= """  50.
 470.24259829   50.          916.00353822   50.11665159
 1341.39745983   50.         1781.15150341   50.         2216.78819124
   50.         2618.72369755   50.         3086.52839647   50.
 3544.76159344 3950.          513.4805063  3950.          922.04256503
 3949.99286289 1324.29085047 3949.99999517 1811.17324159 3949.9999986
 2217.51966454 3949.99999999 2619.46002241 3950.         3090.42082608
 3950.         3502.2831148    50.         3950.          497.80224615
 3949.99998332  905.83957047 3950.         1410.52214847 3950.
 1817.4121967  3950.         2220.25570948 3950.         2662.79843459
 3949.90330246 3070.02379633 3950.         3518.24596686 3949.85218386
 3949.13652122 3950.           50.           50.          485.79236965
   50.          899.38716967   50.         1349.83619794   50.
 1783.29802199   50.00056021 2196.74733557   50.         2698.35227769
   50.         3110.29790903   50.         3525.29867758   50.
 3950.           50.         3233.03627774 3216.628471   1598.79432119
 2442.3470836  2699.04528207 1346.86242966  655.65782508 1141.44788565
  863.02534884 2577.01154325 1922.47387534 3190.46577978 2506.36506365
 1940.17196406 1746.44091753  761.80892573 1276.28379704 1866.37213988
 1224.83797643  668.24273544 3256.13075238  899.87455051 2106.11647958
 1466.62100844 3359.17309107 2137.71922459 1147.60579707 3325.88022099"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;470.24259829&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;916.00353822&#39;, &#39;&#39;, &#39;&#39;, &#39;50.11665159&#39;, &#39;&#39;, &#39;1341.39745983&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;1781.15150341&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;2216.78819124&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;2618.72369755&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;3086.52839647&#39;, &#39;&#39;, &#39;

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.000000   470.242598
1  50.000000   916.003538
2  50.116652  1341.397460
3  50.000000  1781.151503
4  50.000000  2216.788191

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans33.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)