In [2]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [3]:
best_pos='''1599.56777077   93.70696067  977.69086085 3396.74435268 1385.660456
  531.69559985 2152.72829952 3880.75702752 1475.16977927 1828.98303877
  156.2256352   172.12015106 2879.6632848  3224.29584445  580.30376357
 3688.43989335 1396.06929631 2270.6975568  1775.13695957 2112.00022028
 1175.73037279 1233.17003113 1218.70782628 3066.72733004 2332.14457732
  325.94905138 2337.48817619 3517.75127575 3511.48431567  313.43449385
 3368.78037911 2603.46380248 3866.29908888 1925.38475969 3774.19438724
 1511.07574697 3461.77646648  802.85640803 2042.81879021 2808.34950352
 3770.12188504 3101.74269975  746.14373384  150.5462964   750.81296614
 1882.14693237 3223.89166344 1502.6271973   180.61527334 1388.53927504
  670.86268055 2357.21517467 2256.66008049  741.36611718 1177.30852739
 3882.25072579 2715.78245101 1298.93391261 2971.06525856 2487.04235763
  450.90950812  736.11169998 2884.57424705 1785.35243617   93.22534524
 1983.19979709 2961.01578193 3747.47295462 2853.95122113  804.4982058
 3945.07707014 3489.24277505 1652.47307651 1284.27462761  763.88665498
 1237.97117534 2448.166687   2210.76038531 2242.77645543 1603.06975408
 3905.47044191 2698.09870495 1665.43333142 3690.30115181  572.98158952
 3217.26581343  100.8086209  3389.45117619  186.3913866  2750.50123058
 3351.57752029 3408.00774111 3924.39050607   74.17474707  180.54735695
 3820.09163964 3425.80751202 2120.04026762 3881.62212234 1039.68716322'''

In [4]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;1599.56777077&#39;, &#39;&#39;, &#39;&#39;, &#39;93.70696067&#39;, &#39;&#39;, &#39;977.69086085&#39;, &#39;3396.74435268&#39;, &#39;1385.660456&#39;, &#39;&#39;, &#39;&#39;, &#39;531.69559985&#39;, &#39;2152.72829952&#39;, &#39;3880.75702752&#39;, &#39;1475.16977927&#39;, &#39;1828.98303877&#39;, &#39;&#39;, &#39;&#39;, &#39;156.2256352&#39;, &#39;&#39;, &#39;&#39;, &#39;172.12015106&#39;, &#39;2879.6632848&#39;, &#39;&#39;, &#39;3224.29584445&#39;, &#39;&#39;, &#39;580.30376357&#39;, &#39;&#39;, &#39;3688.43989335&#39;, &#39;1396.06929631&#39;, &#39;2270.6975568&#39;, &#39;&#39;, &#39;1775.13695957&#39;, &#39;2112.00022028&#39;, &#39;&#39;, &#39;1175.73037279&#39;, &#39;1233.17003113&#39;, &#39;1218.70782628&#39;, &#39;3066.72733004&#39;, &#39;2332.14457732&#39;, &#39;&#39;, &#39;&#39;, &#39;325.94905138&#39;, &#39;2337.48817619&#39;, &#39;3517.75127575&#39;, &#39;3511.48431567&#39;, &#39;&#39;, &#39;313.43449385&#39;, &#39;&#39;, &#39;3368.78037911&#39;, &#39;2603.46380248&#39

In [5]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [6]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [7]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  1599.567771    93.706961
1   977.690861  3396.744353
2  1385.660456   531.695600
3  2152.728300  3880.757028
4  1475.169779  1828.983039

In [8]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans1.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)