In [1]:
import numpy as np 

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """  50.
 496.87300356   50.          919.18919606   50.
 1359.44656022   50.         1789.85937086   50.43896034 2209.14917956
   50.         2652.73379862   50.         3083.05444252   50.
 3502.86752433 3950.          524.54799119 3950.          926.59740404
 3949.99999979 1332.84395596 3949.89692274 1804.30111036 3950.
 2207.47946035 3949.99998409 2646.99820157 3950.         3078.93997255
 3950.         3515.01693945   50.00487944 3950.          534.13409563
 3950.          954.51276045 3949.99912041 1356.87699218 3949.99999787
 1783.05365099 3950.         2231.96131715 3950.         2666.84322109
 3950.         3120.24965829 3949.99999978 3522.96499011 3950.
 3950.         3948.59985385   50.           50.          486.62158679
   50.00000001  908.67332805   50.00101201 1337.20571108   50.00000108
 1780.78630638   50.         2211.69087987   50.         2698.07256938
   50.         3101.29380144   50.00002011 3515.25049443   50.00052999
 3949.98185176   50.         1090.00947346 2465.14268266 3044.24522801
 1034.90260505 1463.16120147 2023.57364185 2788.91784143 3363.06266355
 2383.60925409 2227.21720426 2495.51054631 1612.32961048 1609.42555641
 3079.1804326  3162.52439443 2391.30910219 1552.46765935 1559.08241778
  556.09187176 1364.46723131 2874.30540491 2864.40260808 2556.59690734
  439.9775557  2058.74199689 3488.75828049 2209.28671952 1130.80071142"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;496.87300356&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;919.18919606&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;1359.44656022&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;1789.85937086&#39;, &#39;&#39;, &#39;&#39;, &#39;50.43896034&#39;, &#39;2209.14917956&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;2652.73379862&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;3083.05444252&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;3502.86752433&#39;, &#39;3950.&#39;, &#39;&#39;, &#39;&#3

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.00000   496.873004
1  50.00000   919.189196
2  50.00000  1359.446560
3  50.00000  1789.859371
4  50.43896  2209.149180

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans27.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)