In [1]:
import numpy as np 

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [8]:
best_pos="""  50.
 481.60221869   50.00426027  918.606692     50.
 1350.22925378   50.         1797.10874665   50.         2217.80085819
   50.         2650.99168318   50.         3053.07138941   50.0000013
 3516.43279766 3950.          481.93863175 3950.          916.72514242
 3950.         1349.87624986 3949.99920538 1792.46849063 3950.
 2217.68357693 3950.         2674.33369721 3950.         3082.08048537
 3950.         3484.21498827   50.         3949.98878652  485.02872661
 3950.          915.45766353 3950.         1346.07602038 3950.
 1780.29873784 3950.         2221.00647662 3950.         2652.67863898
 3950.         3057.78997142 3950.         3521.52937203 3950.
 3949.76162084 3949.99999979   50.           50.02945426  483.21491255
   50.00386841  908.93868884   50.         1347.22451403   50.
 1783.62862244   50.00198451 2216.54786021   50.023814   2650.02386765
   50.         3083.57843349   50.         3516.69420166   50.04333933
 3949.98805764   50.          586.36261914 3333.62768039 3079.32543721
 2314.95319468 2055.38952328 2176.10813147 1552.01639115 1555.14459985
 1379.06527637 3215.09859536 2428.4435614  1600.67090611 1274.70675483
  485.7548488  2529.83417445 2959.65499029  694.28437912 1435.91425946
  871.07144944 2201.16179352 3526.05952741 2142.44230539 1374.4949159
 2032.96903676 1844.49407043 2850.6688162  3102.50554564  823.10482915"""

In [9]:
pos = best_pos.replace('\n', ' ').split(' ')
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))
import numpy as np 
ans = np.array(ans).reshape((50, 2))
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.00000   481.602219
1  50.00426   918.606692
2  50.00000  1350.229254
3  50.00000  1797.108747
4  50.00000  2217.800858

In [10]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans4_all.csv",index=False)

In [22]:
def proxi_constraint(particle):
    """
        Function to penalize if proximity contraint is violated.
        particle : numpy array with shape (n_turbs, 2)
    """
    proxi_penalty = 0
    for i in range(particle.shape[0]-1):  
        for j in range(i+1,particle.shape[0]):
            norm = np.linalg.norm(particle[i]-particle[j])
            if norm < 400: print(particle[i],particle[j])
            proxi_penalty += max(0, 400-norm)  # linear penalty 
            
    return proxi_penalty/(particle.shape[0]*400)    # dividing to normalize the value to between 0 and 1

In [24]:
ans = np.array(pd.read_csv('C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans1_9.csv')).reshape((50,2))
proxi_constraint(ans)

[1337.3326655  3949.99999995] [1288.20161423 3553.25275135]


1.1113120625896045e-05

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
(a+b)/np.sum(a+b)
np.zeros((5,))

array([0., 0., 0., 0., 0.])