In [2]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [14]:
best_pos = """2710.23506009 2757.31061099 3158.07520405 3136.93518067 2859.67338773
 2064.62955872 3854.90368252 3414.77888825 1624.23312437 2648.33706342
 3858.07987048 1351.8921817  1531.55678336 3724.48150182 3272.29953045
 1073.37750855 3214.59310315  663.47893215 2059.16030147 1414.5807111
 3344.71684403 2058.67406385  639.76313717 3579.7027386   135.5379365
  919.77507724 1759.42164863 3186.36764337  827.07110122 2993.51629021
 2223.36871092 2682.45210454  992.77957783 1712.10427361 2660.62269923
 3404.94112367 2489.65154292 1611.56543893 1908.12522856  708.70762573
   78.06119656 2818.83828808 2579.22883117  136.97649139  488.31569247
 1439.38217371 3735.87015335 2856.81167677 3756.94362323 3906.69842916
  234.63273209 3912.1231901   610.97045382  189.26130759 3074.82706377
 3756.59005633  476.41819619 2139.1645761  3695.98475576  225.64521466
 1023.43524359  188.02522337  693.5572742   771.26041617 1604.67228667
 1435.60540127 1725.58866391 1941.68229118 1555.22378626   77.25722837
 3223.78700919  227.3493335    50.14777632 1367.09648512 1135.15546983
  616.82165498   73.34846668 2262.38511133 1094.17034582 3938.90461577
 2434.72529012  662.96198642 1951.66976189 3570.04351301 2850.91198406
  914.98324422 1083.476577   2142.59193861 3905.11590308 2374.82706784
 3859.56265069  934.02991192  225.4913879  3218.14719852 1078.41732649
 3339.85376945 3707.97204582 1756.09454914  122.91064339  249.32961229"""

In [15]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;2710.23506009&#39;, &#39;2757.31061099&#39;, &#39;3158.07520405&#39;, &#39;3136.93518067&#39;, &#39;2859.67338773&#39;, &#39;&#39;, &#39;2064.62955872&#39;, &#39;3854.90368252&#39;, &#39;3414.77888825&#39;, &#39;1624.23312437&#39;, &#39;2648.33706342&#39;, &#39;&#39;, &#39;3858.07987048&#39;, &#39;1351.8921817&#39;, &#39;&#39;, &#39;1531.55678336&#39;, &#39;3724.48150182&#39;, &#39;3272.29953045&#39;, &#39;&#39;, &#39;1073.37750855&#39;, &#39;3214.59310315&#39;, &#39;&#39;, &#39;663.47893215&#39;, &#39;2059.16030147&#39;, &#39;1414.5807111&#39;, &#39;&#39;, &#39;3344.71684403&#39;, &#39;2058.67406385&#39;, &#39;&#39;, &#39;639.76313717&#39;, &#39;3579.7027386&#39;, &#39;&#39;, &#39;&#39;, &#39;135.5379365&#39;, &#39;&#39;, &#39;&#39;, &#39;919.77507724&#39;, &#39;1759.42164863&#39;, &#39;3186.36764337&#39;, &#39;&#39;, &#39;827.07110122&#39;, &#39;2993.51629021&#39;, &#39;&#39;, &#39;2223.36871092&#39;, &#39;2682.45210454&#39;, &#39;&#39;, &#39;992.77957783&#39;, &#39;1712.104273

In [16]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [17]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [18]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  2710.235060  2757.310611
1  3158.075204  3136.935181
2  2859.673388  2064.629559
3  3854.903683  3414.778888
4  1624.233124  2648.337063

In [19]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans5.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)