In [2]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """2711.96696905 1736.80533312 3409.6331616  3009.86405416 3930.74154723
 3949.52000983  694.27105982 2060.80147583 3007.30631857 3950.
 1902.09935979  122.58736735   50.         1290.17039454  995.64890617
 1268.86075128 2441.45902137 3253.73900351 3949.62273066 2713.19536211
 1847.23429751 2543.36929869 2554.04884642 2700.79880407 3374.11988484
   58.33940573 2142.67746131 2230.34840395 3950.         1070.1431782
 3176.77475544 1656.31622688  517.74405606 3904.84330105 1521.06508331
 1095.76485602 2306.965373   3949.9994049  2140.73584759 2885.64202951
 2816.66135219   50.         1348.71336174   50.38429959 3950.
 2057.62603923 3949.96891166  592.57474071   56.00822938 2603.62012992
 2334.34907404   50.19136463 3946.26953591 1529.59684289   50.
 3949.99868376 1672.27505949 3950.         2912.02158441 1217.53247812
 2889.7911979   480.59636625 3949.66628065 3115.76213993 3950.
 3549.44237123   91.64768203  181.73284399 2183.80763848  457.26418183
  475.19235334   50.           50.00000432 3151.46586244   57.40879546
 1938.15428604  994.00652609 3928.24086428 3521.75677964 3949.99993182
 3289.63183097  450.50200136  353.73537985 1660.11714818  376.51419426
  517.30663752  922.62887739   50.37745837 1967.87908584 3380.28849384
  521.45367897 2992.56338123 1091.67241249 3049.18837176 3950.
   50.         3566.95770517 2395.78335175   50.          845.39426641"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;2711.96696905&#39;, &#39;1736.80533312&#39;, &#39;3409.6331616&#39;, &#39;&#39;, &#39;3009.86405416&#39;, &#39;3930.74154723&#39;, &#39;&#39;, &#39;3949.52000983&#39;, &#39;&#39;, &#39;694.27105982&#39;, &#39;2060.80147583&#39;, &#39;3007.30631857&#39;, &#39;3950.&#39;, &#39;&#39;, &#39;1902.09935979&#39;, &#39;&#39;, &#39;122.58736735&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;1290.17039454&#39;, &#39;&#39;, &#39;995.64890617&#39;, &#39;&#39;, &#39;1268.86075128&#39;, &#39;2441.45902137&#39;, &#39;3253.73900351&#39;, &#39;3949.62273066&#39;, &#39;2713.19536211&#39;, &#39;&#39;, &#39;1847.23429751&#39;, &#39;2543.36929869&#39;, &#39;2554.04884642&#39;, &#39;2700.79880407&#39;, &#39;3374.11988484&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;58.33940573&#39;, &#39;2142.67746131&#39;, &#39;2230.34840395&#39;, &#39;3950.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  2711.966969  1736.805333
1  3409.633162  3009.864054
2  3930.741547  3949.520010
3   694.271060  2060.801476
4  3007.306319  3950.000000

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans16.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)