In [2]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """1596.36676121  138.45422947  977.35644651 3397.25279901 1371.66352873
  531.23094872 2152.18943217 3880.48267978 1474.30494376 1761.45855404
  145.77529213  170.86626144 2876.5517584  3241.31656311  578.94637377
 3696.4916067  1392.37092802 2270.59162683 1791.80058046 2126.50828955
 1172.20025507 1233.44428622 1276.35619279 3064.07883597 2331.04998686
  291.76315127 2341.08003751 3525.13647344 3509.74373678  305.91902447
 3407.70024525 2624.86909089 3946.74467453 1925.01922331 3793.66307558
 1507.68448835 3460.18500294  805.0856397  2043.45918015 2815.50631935
 3777.62731713 3084.42720253  762.17779674  148.1203289   749.75514296
 1899.91662296 3224.76477593 1496.4964356   175.77767411 1383.17447608
  672.80551515 2378.38472016 2254.93414603  711.87246433 1178.5008897
 3940.73195026 2717.08265181 1296.4174027  2967.01646509 2489.50022023
  448.92815815  740.20884466 2881.69941061 1785.83880112  185.04395974
 1981.40952189 2969.26296853 3788.86913382 2853.66198343   81.1139672
 3777.68213359 3494.02234882 1652.67730233 1286.64100779  763.13090013
 1241.02433756 2441.31059335 2213.22435888 2240.16807078 1643.18564152
 3918.05982842 2700.55042565 1663.29742039 3692.1217649   577.77003281
 3218.87500349   77.43623195 3390.67835768  163.08420983 2685.67971257
 3314.21289245 3409.40469451 3949.64802346   62.34615667  188.61761936
 3924.88134277 3421.80374792 2099.05083785 3880.06835909 1037.43124051"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;1596.36676121&#39;, &#39;&#39;, &#39;138.45422947&#39;, &#39;&#39;, &#39;977.35644651&#39;, &#39;3397.25279901&#39;, &#39;1371.66352873&#39;, &#39;&#39;, &#39;&#39;, &#39;531.23094872&#39;, &#39;2152.18943217&#39;, &#39;3880.48267978&#39;, &#39;1474.30494376&#39;, &#39;1761.45855404&#39;, &#39;&#39;, &#39;&#39;, &#39;145.77529213&#39;, &#39;&#39;, &#39;170.86626144&#39;, &#39;2876.5517584&#39;, &#39;&#39;, &#39;3241.31656311&#39;, &#39;&#39;, &#39;578.94637377&#39;, &#39;&#39;, &#39;3696.4916067&#39;, &#39;&#39;, &#39;1392.37092802&#39;, &#39;2270.59162683&#39;, &#39;1791.80058046&#39;, &#39;2126.50828955&#39;, &#39;&#39;, &#39;1172.20025507&#39;, &#39;1233.44428622&#39;, &#39;1276.35619279&#39;, &#39;3064.07883597&#39;, &#39;2331.04998686&#39;, &#39;&#39;, &#39;&#39;, &#39;291.76315127&#39;, &#39;2341.08003751&#39;, &#39;3525.13647344&#39;, &#39;3509.74373678&#39;, &#39;&#39;, &#39;305.91902447&#39;, &#39;&#39;, &#39;3407.70024525&#39;, &#39;2624.86909089&#39;, &#39;3946.7446745

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  1596.366761   138.454229
1   977.356447  3397.252799
2  1371.663529   531.230949
3  2152.189432  3880.482680
4  1474.304944  1761.458554

In [7]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans7.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)