In [1]:
import numpy as np 

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """  50.
 496.93888578   50.          918.69868636   50.
 1359.57519902   50.         1790.14929234   50.56357952 2209.20723064
   50.         2653.59135023   50.         3083.11924169   50.
 3503.03265379 3950.          524.53162545 3950.          926.67592402
 3949.99999991 1332.85577522 3949.90565497 1804.29829881 3950.
 2207.77790362 3949.99995547 2647.08077873 3950.         3079.82096007
 3950.         3515.13412769   50.0035842  3950.          534.03511482
 3950.          954.5988959  3949.9995221  1356.88624513 3949.99999952
 1783.06805993 3950.         2231.63355439 3950.         2666.46283835
 3950.         3120.24253881 3949.9999997  3523.3037459  3950.
 3950.         3950.           50.           50.          499.8057287
   50.          907.82536648   50.00061716 1337.11944315   50.
 1766.39316172   50.         2211.45800159   50.         2698.05919882
   50.         3101.26406512   50.00002636 3515.46915651   50.00026593
 3949.9808591    50.         1089.63126429 2465.3128316  3041.83729182
 1035.30863425 1464.36913518 2025.04096184 2788.81421252 3364.05638273
 2383.46998552 2221.66476768 2495.28293331 1611.41558726 1609.2105865
 3079.13422019 3160.89708684 2388.02900399 1552.71700327 1559.99053218
  556.15317078 1365.05923332 2873.85027402 2872.55956133 2555.82976035
  440.86230705 2059.96023836 3488.31086487 2209.75860545 1132.33690385"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;496.93888578&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;918.69868636&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;1359.57519902&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;1790.14929234&#39;, &#39;&#39;, &#39;&#39;, &#39;50.56357952&#39;, &#39;2209.20723064&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;2653.59135023&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;3083.11924169&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;3503.03265379&#39;, &#39;3950.&#39;, &#39;&#39;, &#39;&#3

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.00000   496.938886
1  50.00000   918.698686
2  50.00000  1359.575199
3  50.00000  1790.149292
4  50.56358  2209.207231

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans31_1.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)