In [1]:
import numpy as np 

In [11]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.append(a, [[1, 2], [3, 4]]).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [4]:
b = np.append(a, [4, 5])

In [5]:
b

array([1, 2, 3, 4, 5])

In [7]:
b[0] = 0
a

array([1, 2, 3])

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """ 50.01175185  495.56381299   50.05250137  921.13091863   51.60207214
 1340.21820359   52.97046221 1771.78445434   50.39610854 2215.85447723
   50.34076082 2618.97350626   50.02088251 3105.96845389   50.548929
 3541.55550112 3950.          512.52390004 3950.          920.43023295
 3950.         1325.27808866 3950.         1800.09965661 3950.
 2204.13195472 3950.         2640.50835378 3950.         3051.47853195
 3950.         3470.47779694   50.10581092 3950.          513.80694996
 3950.          975.68060655 3950.         1398.20527087 3949.75475801
 1809.01227979 3950.         2220.99293393 3950.         2664.57427245
 3950.         3073.93431999 3950.         3516.5280437  3950.
 3950.         3950.           50.37141636   50.10022429  487.64232328
   50.53268364  899.19301278   50.30074272 1338.12934721   50.
 1772.86356925   50.23067644 2181.73496117   50.27797284 2696.91797314
   50.37793329 3114.34318549   50.20201891 3525.23137015   50.05315724
 3950.           50.00307038 1572.15040971 1572.52614401 2418.32681442
 1561.61190932"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))
import numpy as np 
ans = np.array(ans).reshape((38, 2))
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.011752   495.563813
1  50.052501   921.130919
2  51.602072  1340.218204
3  52.970462  1771.784454
4  50.396109  2215.854477

In [3]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/PSO/xyz.csv",index=False)

In [22]:
def proxi_constraint(particle):
    """
        Function to penalize if proximity contraint is violated.
        particle : numpy array with shape (n_turbs, 2)
    """
    proxi_penalty = 0
    for i in range(particle.shape[0]-1):  
        for j in range(i+1,particle.shape[0]):
            norm = np.linalg.norm(particle[i]-particle[j])
            if norm < 400: print(particle[i],particle[j])
            proxi_penalty += max(0, 400-norm)  # linear penalty 
            
    return proxi_penalty/(particle.shape[0]*400)    # dividing to normalize the value to between 0 and 1

In [24]:
ans = np.array(pd.read_csv('C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans1_9.csv')).reshape((50,2))
proxi_constraint(ans)

[1337.3326655  3949.99999995] [1288.20161423 3553.25275135]


1.1113120625896045e-05

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
(a+b)/np.sum(a+b)
np.zeros((5,))

array([0., 0., 0., 0., 0.])