In [2]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos = """  50.
 464.1998797    50.          916.84626176   50.
 1349.2464081    50.         1793.55552675   50.00243274 2196.61992114
   50.00322259 2650.24328594   50.         3091.27044532   50.
 3516.17633675 3950.          483.42797607 3950.          932.76653572
 3950.         1349.50538756 3949.99999793 1783.43616206 3950.
 2216.64264497 3950.         2649.98266281 3950.         3085.0609407
 3949.99825891 3516.12345032   50.00692359 3949.99991362  525.71558522
 3950.          930.60974666 3950.         1343.40441571 3950.
 1758.90843945 3950.         2200.25099393 3950.         2648.74138667
 3949.90155607 3078.70134284 3949.99623247 3502.08030484 3950.
 3949.9782458  3950.           50.02846592   50.          485.28840349
   50.01654823  901.03227194   50.         1361.937687     50.00000225
 1764.3007004    50.         2240.57943459   50.         2675.56961992
   50.         3084.49569713   50.         3516.55844692   50.
 3950.           50.00006555 2673.1559426   857.26037807 1194.21264631
 1395.05443941 2590.82318262 1986.65287366 3344.38494709 3490.82927421
 1237.71084121  623.01890877 3474.51554591 2651.84049343 1090.55293748
 2383.62988598 1876.59474527 1991.86769981 3092.86721471 1213.55413967
 2324.89967127 1502.38034934 1855.60684402 3096.25182412  695.98122361
 1587.35475151 2130.41015485 2605.4041358  1480.10552249 3316.81667433"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;464.1998797&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;916.84626176&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;1349.2464081&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;1793.55552675&#39;, &#39;&#39;, &#39;&#39;, &#39;50.00243274&#39;, &#39;2196.61992114&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;50.00322259&#39;, &#39;2650.24328594&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;3091.27044532&#39;, &#39;&#39;, &#39;&#39;, &#39;50.&#39;, &#39;&#39;, &#39;3516.17633675&#39;, &#39;3950.&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#

In [3]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [4]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [5]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.000000   464.199880
1  50.000000   916.846262
2  50.000000  1349.246408
3  50.000000  1793.555527
4  50.002433  2196.619921

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans23.csv",index=False)

In [4]:
swarm = np.array(pd.read_csv('oswarm0.csv'))
swarm.shape

(64, 100)