In [1]:
import numpy as np 

In [19]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [20]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [21]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [28]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [31]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [33]:
np.random.uniform(50,3950,2)

array([3892.56125629, 2405.42328721])