In [1]:
import numpy as np 

In [11]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.append(a, [[1, 2], [3, 4]]).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [4]:
b = np.append(a, [4, 5])

In [5]:
b

array([1, 2, 3, 4, 5])

In [7]:
b[0] = 0
a

array([1, 2, 3])

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [4]:
best_pos = """ 50.   
       514.8505663    50.00154409  917.0329181    50.15718493
 1338.03639303   50.00236155 1825.54093887   50.         2245.86900148
   50.71689549 2678.4081447    50.63727104 3088.52125099   50.2004677
 3518.39962095 3950.          479.7821211  3950.          917.89256708
 3950.         1349.83354777 3950.         1815.00765515 3950.
 2219.35837379 3950.         2639.98456778 3950.         3046.79304796
 3950.         3525.35691789   50.00027331 3950.          519.73573306
 3950.          931.77505063 3950.         1336.74412442 3950.
 1763.03428185 3950.         2227.56032673 3950.         2646.9152007
 3950.         3076.24198159 3950.         3486.56619909 3950.
 3950.         3950.           50.           50.34932334  476.81023011
   50.30026481  901.3348141    50.02139791 1326.98058223   50.36030804
 1809.95531264   50.         2230.13154491   50.04762471 2639.13858733
   50.         3065.51537044   50.02906902 3478.72266201   50.00477579
 3950.           50.0019506  1573.19151544 1581.04854097 2408.78779162
 2435.96648554"""

In [5]:
pos = best_pos.replace('\n', ' ').split(' ')
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))
import numpy as np 
ans = np.array(ans).reshape((38, 2))
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.000000   514.850566
1  50.001544   917.032918
2  50.157185  1338.036393
3  50.002362  1825.540939
4  50.000000  2245.869001

In [6]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/PSO/brute_force2.csv",index=False)

In [22]:
def proxi_constraint(particle):
    """
        Function to penalize if proximity contraint is violated.
        particle : numpy array with shape (n_turbs, 2)
    """
    proxi_penalty = 0
    for i in range(particle.shape[0]-1):  
        for j in range(i+1,particle.shape[0]):
            norm = np.linalg.norm(particle[i]-particle[j])
            if norm < 400: print(particle[i],particle[j])
            proxi_penalty += max(0, 400-norm)  # linear penalty 
            
    return proxi_penalty/(particle.shape[0]*400)    # dividing to normalize the value to between 0 and 1

In [24]:
ans = np.array(pd.read_csv('C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans1_9.csv')).reshape((50,2))
proxi_constraint(ans)

[1337.3326655  3949.99999995] [1288.20161423 3553.25275135]


1.1113120625896045e-05

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
(a+b)/np.sum(a+b)
np.zeros((5,))

array([0., 0., 0., 0., 0.])