In [1]:
import numpy as np 

In [11]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
np.append(a, [[1, 2], [3, 4]]).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [4]:
b = np.append(a, [4, 5])

In [5]:
b

array([1, 2, 3, 4, 5])

In [7]:
b[0] = 0
a

array([1, 2, 3])

In [30]:
np.random.randint(7,9,4)

array([7, 7, 8, 7])

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [1]:
import pandas as pd

In [8]:
np.array(np.array([1, 2, 3]))

array([1, 2, 3])

In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [1]:
best_pos="""  50.       
   483.33331602   50.          916.66667087   50.
 1349.9999895    50.         1783.33346653   50.         2216.66661144
   50.         2649.99968879   50.         3083.33292174   50.
 3516.66669214 3950.          483.32524849 3950.          916.66573552
 3950.         1349.99995059 3950.         1783.33297822 3950.
 2216.66649955 3950.         2650.00000409 3950.         3083.3326742
 3950.         3516.66665652   50.         3950.          483.3327918
 3950.          916.66689002 3950.         1350.00000409 3950.
 1783.32825436 3950.         2216.66666316 3950.         2650.00336439
 3950.         3083.44081166 3950.         3516.66679804 3950.
 3950.         3950.           50.           50.          483.33326935
   50.          916.66322185   50.         1349.98949031   50.
 1783.33332064   50.         2216.66717313   50.         2649.99992704
   50.         3083.3336014    50.         3516.6656257    50.
 3950.           50.         3125.63698403 2480.06032884 2248.07619151
 1432.99826846 3280.96779146 1126.61282564 1327.91418626 3189.24671141
 3168.65972987 3332.52627251 1359.7557589  2481.00134176 1076.73445696
 1811.45467224 2431.70069889 3071.00328921 2903.10162411  806.20810177
 1770.53245997 2815.02510609 1352.6164944   746.0504991  1492.04026914
 1735.96995453  660.78966346 2551.31447877 2730.97850088 1988.17022847"""

In [2]:
pos = best_pos.replace('\n', ' ').split(' ')
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))
import numpy as np 
ans = np.array(ans).reshape((50, 2))
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  50.0   483.333316
1  50.0   916.666671
2  50.0  1349.999990
3  50.0  1783.333467
4  50.0  2216.666611

In [3]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/trial0.csv",index=False)

In [22]:
def proxi_constraint(particle):
    """
        Function to penalize if proximity contraint is violated.
        particle : numpy array with shape (n_turbs, 2)
    """
    proxi_penalty = 0
    for i in range(particle.shape[0]-1):  
        for j in range(i+1,particle.shape[0]):
            norm = np.linalg.norm(particle[i]-particle[j])
            if norm < 400: print(particle[i],particle[j])
            proxi_penalty += max(0, 400-norm)  # linear penalty 
            
    return proxi_penalty/(particle.shape[0]*400)    # dividing to normalize the value to between 0 and 1

In [24]:
ans = np.array(pd.read_csv('C:/Users/awals/Downloads/Shell AI Hackathon/Trials/opt_swarm_ans1_9.csv')).reshape((50,2))
proxi_constraint(ans)

[1337.3326655  3949.99999995] [1288.20161423 3553.25275135]


1.1113120625896045e-05

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
(a+b)/np.sum(a+b)
np.zeros((5,))

array([0., 0., 0., 0., 0.])