In [1]:
import numpy as np 

In [2]:
a = np.array([[1, 1]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a, b)

[[1 1]] [[1 1]
 [2 2]
 [3 3]]


In [3]:
np.linalg.norm(b - a,axis=1)

array([0.        , 1.41421356, 2.82842712])

In [4]:
b[2,:] = a
b

array([[1, 1],
       [2, 2],
       [1, 1]])

In [5]:
c = b.flatten()
c

array([1, 1, 2, 2, 1, 1])

In [6]:
c.reshape((3,2))

array([[1, 1],
       [2, 2],
       [1, 1]])

In [7]:
np.random.uniform(50,3950,2)

array([ 734.48139515, 3862.51395608])

In [11]:
a = np.array([1, 2, 3, 4])
c = np.array(a.reshape((2,2)))
c[:,1] = [0, 0]
a

array([1, 2, 3, 4])

In [12]:
c

array([[1, 0],
       [3, 0]])

In [2]:
best_pos = '''3647.31441586 2662.35356308 3342.83874774 1405.83112209 1206.21987918
 3503.1499872  3648.97476571 2171.22336612 1286.50718121  354.80638677
 2414.12228876 2547.90800992  261.24346745 2296.021812    651.43578431
 3845.94715716 2909.03802949 3533.87031901 3259.41817159  104.03393781
  175.56601604  757.88115313 2722.07153834  102.17201954 1569.62495512
 3803.84042411 1636.49076564 1167.89189118  111.90087394 1529.72011124
  754.19353167  997.95428497 2579.33244123 1489.81048438 1254.47305847
 2979.46820525  730.85210496 2475.46434362  511.8878365   169.74272156
 3437.22125014  637.57769473 1967.50374282 1706.89240076 3554.62977502
 3808.40405534 2267.47982406  721.3892061  3856.42598825  589.92458179
 2105.38410878 3381.70998313 1255.65162248 1805.02645417 3132.72836853
 1988.91633177 1654.9739873  2260.87258162 2817.10186946 2391.33738827
 1748.02356341 2939.2085232  1687.43533916  179.14390568  155.99356542
 3800.68674777 2031.07486589 3838.54036488 3946.02608025   77.75207781
 3891.74152103 3231.98762075 2843.34128021  876.42041022 3702.714869
 1657.99666731 2756.04267944 3104.81013369  736.6566859  3166.49703091
 2146.6781294  2116.04065083  338.86050277 3333.03915204  534.99897537
 1637.51761099 1851.1289787   670.26678593 2609.36219689 3818.90918877
 1192.36243933 1095.2981504  3186.66956154 3132.47386799  304.36144313
 2713.49139718  923.39031369  158.96146752 3940.3829946  1056.38630133'''

In [6]:
pos = best_pos.replace('\n', ' ').split(' ')
print(pos)

[&#39;3647.31441586&#39;, &#39;2662.35356308&#39;, &#39;3342.83874774&#39;, &#39;1405.83112209&#39;, &#39;1206.21987918&#39;, &#39;&#39;, &#39;3503.1499872&#39;, &#39;&#39;, &#39;3648.97476571&#39;, &#39;2171.22336612&#39;, &#39;1286.50718121&#39;, &#39;&#39;, &#39;354.80638677&#39;, &#39;&#39;, &#39;2414.12228876&#39;, &#39;2547.90800992&#39;, &#39;&#39;, &#39;261.24346745&#39;, &#39;2296.021812&#39;, &#39;&#39;, &#39;&#39;, &#39;&#39;, &#39;651.43578431&#39;, &#39;&#39;, &#39;3845.94715716&#39;, &#39;2909.03802949&#39;, &#39;3533.87031901&#39;, &#39;3259.41817159&#39;, &#39;&#39;, &#39;104.03393781&#39;, &#39;&#39;, &#39;&#39;, &#39;175.56601604&#39;, &#39;&#39;, &#39;757.88115313&#39;, &#39;2722.07153834&#39;, &#39;&#39;, &#39;102.17201954&#39;, &#39;1569.62495512&#39;, &#39;&#39;, &#39;3803.84042411&#39;, &#39;1636.49076564&#39;, &#39;1167.89189118&#39;, &#39;&#39;, &#39;111.90087394&#39;, &#39;1529.72011124&#39;, &#39;&#39;, &#39;&#39;, &#39;754.19353167&#39;, &#39;&#39;, &#39;997

In [10]:
ans = []
for val in pos:
    if val != '':
        ans.append(float(val))

In [13]:
import numpy as np 
ans = np.array(ans).reshape((50, 2))

In [14]:
import pandas as pd 
turbines = pd.DataFrame(ans,columns=['x','y'])
turbines.head()

x            y
0  3647.314416  2662.353563
1  3342.838748  1405.831122
2  1206.219879  3503.149987
3  3648.974766  2171.223366
4  1286.507181   354.806387

In [15]:
# turbines.to_csv("C:/Users/awals/Downloads/Shell AI Hackathon/Trials/2Oct_swarm_ans.csv",index=False)